-- helpful example located here:
-- https://github.com/Snowflake-Labs/sfguide-getting-started-weaviate-on-spcs/blob/main/guides/weaviate-generative-feedback-loop.md

-- OAuth Integration --
USE ROLE ACCOUNTADMIN;
CREATE SECURITY INTEGRATION SNOWSERVICES_INGRESS_OAUTH
  TYPE=oauth
  OAUTH_CLIENT=snowservices_ingress
  ENABLED=true;

-- Bind Service Grant
USE ROLE ACCOUNTADMIN;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN;

-- Weaviate Database --
-- + image repo --
-- + stages --

USE DATABASE PROCURE_AGENT;
CREATE IMAGE REPOSITORY PROCURE_AGENT.PUBLIC.PROCURE_REPO;
CREATE OR REPLACE STAGE YAML_STAGE;
CREATE OR REPLACE STAGE DATA ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');
CREATE OR REPLACE STAGE FILES ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

-- Grants for Weaviate Role
USE ROLE SECURITYADMIN;
GRANT ALL PRIVILEGES ON DATABASE PROCURE_AGENT TO PROCURE_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA PROCURE_AGENT.PUBLIC TO PROCURE_ROLE;
GRANT ALL PRIVILEGES ON WAREHOUSE PROCURE_WAREHOUSE TO PROCURE_ROLE;
GRANT ALL PRIVILEGES ON STAGE PROCURE_AGENT.PUBLIC.FILES TO PROCURE_ROLE;
GRANT ALL PRIVILEGES ON STAGE PROCURE_AGENT.PUBLIC.REVIEW_DATA TO PROCURE_ROLE;

-- External Access Integration
USE ROLE ACCOUNTADMIN;
USE DATABASE PROCURE_AGENT;
USE SCHEMA PUBLIC;
CREATE NETWORK RULE allow_all_rule
  TYPE = 'HOST_PORT'
  MODE= 'EGRESS'
  VALUE_LIST = ('0.0.0.0:443','0.0.0.0:80');

CREATE EXTERNAL ACCESS INTEGRATION allow_all_eai
  ALLOWED_NETWORK_RULES=(allow_all_rule)
  ENABLED=TRUE;

GRANT USAGE ON INTEGRATION allow_all_eai TO ROLE SYSADMIN;

-- Set Up Compute Pools
-- Compute Pools --
USE ROLE SYSADMIN;
CREATE COMPUTE POOL IF NOT EXISTS WEAVIATE_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = true;

CREATE COMPUTE POOL IF NOT EXISTS TEXT2VEC_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = GPU_NV_S
  AUTO_RESUME = true;
  
CREATE COMPUTE POOL IF NOT EXISTS RETRIEVAL_APP_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_S
  AUTO_RESUME = true;

-- creation of Services --
USE ROLE SYSADMIN;
USE DATABASE PROCURE_AGENT;
USE SCHEMA PUBLIC;

CREATE SERVICE WEAVIATE
  IN COMPUTE POOL WEAVIATE_COMPUTE_POOL 
  FROM @YAML_STAGE
  SPEC='weaviate.yaml'
  MIN_INSTANCES=1
  MAX_INSTANCES=1;

CREATE SERVICE TEXT2VEC
  IN COMPUTE POOL TEXT2VEC_COMPUTE_POOL 
  FROM @YAML_STAGE
  SPEC='text2vec.yaml'
  MIN_INSTANCES=1
  MAX_INSTANCES=1;

CREATE SERVICE RETRIEVAL_APP
  IN COMPUTE POOL RETRIEVAL_APP_COMPUTE_POOL 
  FROM @YAML_STAGE
  SPEC='retrieval_app.yaml'
  MIN_INSTANCES=1
  MAX_INSTANCES=1
  EXTERNAL_ACCESS_INTEGRATIONS=(ALLOW_ALL_EAI)
  ;

USE ROLE SECURITYADMIN;
GRANT USAGE ON SERVICE PROCURE_AGENT.PUBLIC.WEAVIATE TO ROLE PROCURE_ROLE;
GRANT USAGE ON SERVICE PROCURE_AGENT.PUBLIC.TEXT2VEC TO ROLE PROCURE_ROLE;
GRANT USAGE ON SERVICE PROCURE_AGENT.PUBLIC.RETRIEVAL_APP TO ROLE PROCURE_ROLE;

SHOW SERVICES;


-- commands for altering services
USE ROLE SYSADMIN; 
USE DATABASE PROCURE_AGENT;

ALTER service WEAVIATE suspend;
ALTER service TEXT2VEC suspend;
ALTER service RETRIEVAL_APP suspend;

ALTER service TEXT2VEC resume;
ALTER service WEAVIATE resume;
ALTER service RETRIEVAL_APP resume;

-- show all compute pools
SHOW COMPUTE POOLS;

ALTER COMPUTE POOL WEAVIATE_COMPUTE_POOL suspend;
ALTER COMPUTE POOL TEXT2VEC_COMPUTE_POOL suspend;
ALTER COMPUTE POOL RETRIEVAL_APP_COMPUTE_POOL suspend;

ALTER COMPUTE POOL WEAVIATE_COMPUTE_POOL resume;
ALTER COMPUTE POOL TEXT2VEC_COMPUTE_POOL resume;
ALTER COMPUTE POOL RETRIEVAL_APP_COMPUTE_POOL resume;

-- Show endpoints 
USE ROLE SYSADMIN;
SHOW ENDPOINTS IN SERVICE PROCURE_AGENT.PUBLIC.JUPYTER;
SHOW ENDPOINTS IN SERVICE PROCURE_AGENT.PUBLIC.WEAVIATE;
SHOW ENDPOINTS IN SERVICE PROCURE_AGENT.PUBLIC.TEXT2VEC;
SHOW ENDPOINTS IN SERVICE PROCURE_AGENT.PUBLIC.PROCURE_APP;
SHOW ENDPOINTS IN SERVICE PROCURE_AGENT.PUBLIC.RETRIEVAL_APP;

DESCRIBE SERVICE PROCURE_AGENT.PUBLIC.JUPYTER;
DESCRIBE SERVICE PROCURE_AGENT.PUBLIC.TEXT2VEC;
DESCRIBE SERVICE PROCURE_AGENT.PUBLIC.WEAVIATE;
DESCRIBE SERVICE PROCURE_AGENT.PUBLIC.RETRIEVAL_APP;


-- See service status and logs
USE DATABASE procure_agent;
USE SCHEMA public;
CALL SYSTEM$GET_SERVICE_LOGS('text2vec', '0', 'text2vec', 10);
CALL SYSTEM$GET_SERVICE_STATUS('text2vec');

CALL SYSTEM$GET_SERVICE_STATUS('weaviate');
CALL SYSTEM$GET_SERVICE_LOGS('weaviate', '0', 'weaviate', 10);

CALL SYSTEM$GET_SERVICE_LOGS('jupyter', '0', 'jupyter', 10);

CALL SYSTEM$GET_SERVICE_LOGS('retrieval_app', '0', 'retrieval-app', 10);
CALL SYSTEM$GET_SERVICE_STATUS('retrieval_app');


-- drops all the services
--ALTER COMPUTE POOL WEAVIATE_COMPUTE_POOL STOP ALL;
--ALTER COMPUTE POOL TEXT2VEC_COMPUTE_POOL STOP ALL;
--ALTER COMPUTE POOL JUPYTER_COMPUTE_POOL STOP ALL;

--DROP SERVICE PROCURE_AGENT.PUBLIC.WEAVIATE;
--DROP SERVICE PROCURE_AGENT.PUBLIC.JUPYTER;
--DROP SERVICE PROCURE_AGENT.PUBLIC.TEXT2VEC;
--DROP SERVICE PROCURE_AGENT.PUBLIC.RETRIEVAL_APP;



